let weather = {
  "grass": "sunny_clear",
  "fire": "sunny_clear",
  "ground": "sunny_clear",
  "water": "rainy",
  "electric": "rainy",
  "bug": "rainy",
  "normal": "partly_cloudy",
  "rock": "partly_cloudy",
  "fairy": "cloudy",
  "fighting": "cloudy",
  "poison": "cloudy",
  "flying": "windy",
  "dragon": "windy",
  "psychic": "windy",
  "ice": "snow",
  "steel": "snow",
  "dark": "fog",
  "ghost": "fog"
}